/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.96
 * Generated at: 2024-11-15 10:50:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.shop;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Vector;
import beans.BookBean;
import beans.ReviewBean;

public final class shop02_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("beans.BookBean");
    _jspx_imports_classes.add("java.util.Vector");
    _jspx_imports_classes.add("beans.ReviewBean");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      book.BookInfoMgr bMgr = null;
      bMgr = (book.BookInfoMgr) _jspx_page_context.getAttribute("bMgr", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (bMgr == null){
        bMgr = new book.BookInfoMgr();
        _jspx_page_context.setAttribute("bMgr", bMgr, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');

	request.setCharacterEncoding("UTF-8");

	//로그인 상태 확인
	int userid = 0; 
	
	if(session.getAttribute("idKeyS") !=null){
		//세션값 int로 저장 
		Object sessionValue = session.getAttribute("idKeyS");
		
		// 타입 확인 후 변환
		if (sessionValue instanceof String) {
		    String strValue = (String) sessionValue; // String으로 캐스팅
		    try {
		        userid = Integer.parseInt(strValue);
		    } catch (NumberFormatException e) {
		        e.printStackTrace(); // 변환 실패 시 예외 처리
		    }
		} else if (sessionValue instanceof Integer) {
		    // 만약 세션에 직접 Integer로 저장되어 있다면
		    userid = (Integer) sessionValue; 
		} 
	} 
	
	

	int bookid = Integer.parseInt(request.getParameter("bookid"));
	Vector<BookBean> vlist = null;
	vlist = bMgr.getBook(bookid);
	BookBean bean = vlist.get(0);
	
	//책 정보 가져오기
	String imgUrl = "/image?bookid="+bookid;
	String tit = bean.getTitle();
	String author = bean.getAuthor();
	int price = bean.getPrice();
	int score = bean.getScore();
	String pdate = bean.getPublish_date();
	String category = bean.getCategory();
	String genre = bean.getGenre();
	String contents = bean.getContents();
	String ctable = bean.getContentsTables();
	String aIntro = bean.getAuthorIntro();
	String isbn = bean.getIsbn();
	int pages = bean.getPages();
	
	//한줄평 총 개수 
	int totalReview = bMgr.totalReview(bookid);

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/reset.css?after\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/shop02.css?after\" />\r\n");
      out.write("  <title>상품 상세 페이지</title>\r\n");
      out.write("  <script src=\"https://kit.fontawesome.com/9698826605.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("  <script defer src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/shop02.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<div id=\"wrap\">\r\n");
      out.write("	  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../components/header.jsp", out, false);
      out.write("\r\n");
      out.write("	  <section class=\"shop-product\">\r\n");
      out.write("	    <form name=\"quickFrm\" method=\"post\">\r\n");
      out.write("	      <div>\r\n");
      out.write("	        <p>");
      out.print(tit);
      out.write("</p>\r\n");
      out.write("	        <p>총 금액<span class=\"quick-total\"></span></p>\r\n");
      out.write("	        <button onclick=\"toBuy(event)\">바로구매</button>\r\n");
      out.write("	        <button onclick=\"toCart(event)\">장바구니</button>\r\n");
      out.write("	        <button onclick=\"toWish(event)\">관심목록</button>\r\n");
      out.write("	      </div>\r\n");
      out.write("	      <input type=\"hidden\" name=\"bookid\" value=\"");
      out.print(bookid);
      out.write("\" />\r\n");
      out.write("	    </form><!--form name=\"quickFrm\"-->\r\n");
      out.write("	\r\n");
      out.write("	    <h2>\r\n");
      out.write("	      <i class=\"fa-solid fa-chevron-left\"></i>\r\n");
      out.write("	      <span>");
      out.print(tit);
      out.write("</span>\r\n");
      out.write("	    </h2>\r\n");
      out.write("	    <p>지은이 : <span>");
      out.print(author);
      out.write("</span></p>\r\n");
      out.write("	    <p>");
      out.print(pdate);
      out.write(" 출판</p>\r\n");
      out.write("	    <div class=\"headbook\">\r\n");
      out.write("	      <img src=\"");
      out.print(imgUrl);
      out.write("\" alt=\"");
      out.print(tit);
      out.write("\">\r\n");
      out.write("	      \r\n");
      out.write("	      <form name=\"orderFrm\" method=\"post\">\r\n");
      out.write("	        <h3>가격 : <span>");
      out.print(price);
      out.write("</span>원</h3>\r\n");
      out.write("	        <p>\r\n");
      out.write("	          포인트 :\r\n");
      out.write("	          <span class=\"point\"></span>원 적립 (판매가의 10% 적립)\r\n");
      out.write("	        </p>\r\n");
      out.write("	        <p>배송료 : 2000원<span>(5만원 이상 무료배송)</span></p>\r\n");
      out.write("	        <p>\r\n");
      out.write("	          ");

	        		for(int c=0; c<score; c++){//별생성
	        			
      out.write("\r\n");
      out.write("	        			<i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("	        			");

	        		}//for - make colorstar
	        		for(int e=0; e<5-score; e++){
	        			
      out.write("\r\n");
      out.write("	        			<i class=\"fa-regular fa-star\"></i>\r\n");
      out.write("	        			");
 
	        		}//for - make emptystar
	        	
      out.write("\r\n");
      out.write("	          <span>");
      out.print(score);
      out.write("</span>\r\n");
      out.write("	          <a href=\"#\" class=\"scroll-oneReview\">한줄평(<span>");
      out.print(totalReview);
      out.write("</span>)</a>\r\n");
      out.write("	        </p>\r\n");
      out.write("	\r\n");
      out.write("	        <div class=\"order-qty\">\r\n");
      out.write("	          <div class=\"updown-qty\">\r\n");
      out.write("	            <p>수량 : </p>\r\n");
      out.write("	            <input type=\"text\" name=\"orderNum\" value=\"1\"/>\r\n");
      out.write("	            <div class=\"btn-updown\">\r\n");
      out.write("	              <button type=\"button\">+</button>\r\n");
      out.write("	              <button type=\"button\">-</button>\r\n");
      out.write("	            </div><!--btn-updown-->\r\n");
      out.write("	          </div><!--updown-qty-->\r\n");
      out.write("	          <p>\r\n");
      out.write("	            <span class=\"pretotal\"></span>\r\n");
      out.write("	            <span></span>\r\n");
      out.write("	            <i class=\"fa-solid fa-arrow-right\"></i>\r\n");
      out.write("	          	총 금액\r\n");
      out.write("	            <span class=\"total-price\"></span>\r\n");
      out.write("	          </p>\r\n");
      out.write("	        </div><!--order-qty-->\r\n");
      out.write("	        <input type=\"hidden\" name=\"bookid\" value=\"");
      out.print(bookid);
      out.write("\" />\r\n");
      out.write("	        <div class=\"btns-quickbuy\">\r\n");
      out.write("	          <button onclick=\"toBuy(event)\">바로구매</button>\r\n");
      out.write("	          <button onclick=\"toCart(event)\">장바구니</button>\r\n");
      out.write("	          <button onclick=\"toWish(event)\">관심목록</button>\r\n");
      out.write("	        </div><!--.btns-quickbuy-->\r\n");
      out.write("	        <input type=\"hidden\" name=\"bookid\" value=\"");
      out.print(bookid);
      out.write("\" />\r\n");
      out.write("	      </form>\r\n");
      out.write("\r\n");
      out.write("	    </div><!--.headbook-->\r\n");
      out.write("	\r\n");
      out.write("	    <ul>\r\n");
      out.write("	      <li>\r\n");
      out.write("	        <h3>기본정보</h3>\r\n");
      out.write("	        <p>\r\n");
      out.write("	          전체 페이지 수 : ");
      out.print(pages);
      out.write("쪽<br />\r\n");
      out.write("	          1942gISBN : ");
      out.print(isbn);
      out.write("<br />\r\n");
      out.write("	          주제 분류<br />\r\n");
      out.write("	          <a href=\"/shop/shop01?category=");
      out.print(category);
      out.write('"');
      out.write('>');
      out.print(category);
      out.write("</a> > \r\n");
      out.write("	          <a href=\"/shop/shop01?category=");
      out.print(category);
      out.write("&genre=");
      out.print(genre);
      out.write('"');
      out.write('>');
      out.print(genre);
      out.write("</a>\r\n");
      out.write("	        </p>\r\n");
      out.write("	      </li>\r\n");
      out.write("	      <li>\r\n");
      out.write("	        <h3>이벤트</h3>\r\n");
      out.write("	        <div class=\"container-events\">\r\n");
      out.write("	          <div class=\"slide-events\">\r\n");
      out.write("	            <article>\r\n");
      out.write("	              <a href=\"#\">\r\n");
      out.write("	                <div class=\"img-event\">\r\n");
      out.write("	                </div>\r\n");
      out.write("	                <h4>IT 신간.스테디셀러 대상도서 2만원 이상 구매시 위스키 글라스</h4>\r\n");
      out.write("	              </a>\r\n");
      out.write("	            </article>\r\n");
      out.write("	            <article>\r\n");
      out.write("	              <a href=\"#\">\r\n");
      out.write("	                <div class=\"img-event\">\r\n");
      out.write("	                </div>\r\n");
      out.write("	                <h4>함께 사면 무료배송. 1천원~4천원대 굿즈 총집합</h4>\r\n");
      out.write("	              </a>\r\n");
      out.write("	            </article>\r\n");
      out.write("	            <article>\r\n");
      out.write("	              <a href=\"#\">\r\n");
      out.write("	                <div class=\"img-event\">\r\n");
      out.write("	                </div>\r\n");
      out.write("	                <h4>한빛미디어 IT브랜드전. 다양한 사무용품도 함께 가져가기</h4>\r\n");
      out.write("	              </a>\r\n");
      out.write("	            </article>\r\n");
      out.write("	            <article>\r\n");
      out.write("	              <a href=\"#\">\r\n");
      out.write("	                <div class=\"img-event\">\r\n");
      out.write("	                </div>\r\n");
      out.write("	                <h4>8월 특별 선물. 1박2일 보스턴백 &sdot;피크닉 매트(이벤트 도서 포함 국내서&sdot;외서 5만원 이상)</h4>\r\n");
      out.write("	              </a>\r\n");
      out.write("	            </article>\r\n");
      out.write("	            <article>\r\n");
      out.write("	              <a href=\"#\">\r\n");
      out.write("	                <div class=\"img-event\">\r\n");
      out.write("	                </div>\r\n");
      out.write("	                <h4>이 달의 퀴즈 적립금</h4>\r\n");
      out.write("	              </a>\r\n");
      out.write("	            </article>\r\n");
      out.write("	            <article>\r\n");
      out.write("	              <a href=\"#\">\r\n");
      out.write("	                <div class=\"img-event\">\r\n");
      out.write("	                </div>\r\n");
      out.write("	                <h4>대학교재.토익.자격증.취업 교재 5만원 이상 구매 시</h4>\r\n");
      out.write("	              </a>\r\n");
      out.write("	            </article>\r\n");
      out.write("	\r\n");
      out.write("	          </div><!--.slide-events-->\r\n");
      out.write("	          <div class=\"page-dots\">\r\n");
      out.write("	            <a href=\"#\" class=\"on\"></a>\r\n");
      out.write("	            <a href=\"#\"></a>\r\n");
      out.write("	          </div><!--.page-dots-->\r\n");
      out.write("	        </div><!--.container-events-->\r\n");
      out.write("	      </li>\r\n");
      out.write("	      <li>\r\n");
      out.write("	        <h3>책소개</h3>\r\n");
      out.write("	        <p>");
      out.print(contents);
      out.write("</p>\r\n");
      out.write("	      </li>\r\n");
      out.write("	      <li>\r\n");
      out.write("	        <h3>목차</h3>\r\n");
      out.write("	        <ol>\r\n");
      out.write("	        ");

	        	//DB저장된 목차: 문자열 -> 쉼표 and 띄어쓰기 별로 나누기
	        	String[] ctableArr = ctable.split(",|\\n");
	        	
	        
	        	for(int i=0; i<ctableArr.length; i++){
	        		
	        		
      out.write("\r\n");
      out.write("	        		<li>");
      out.print(ctableArr[i]);
      out.write("</li>\r\n");
      out.write("	        		");

	        	}
	        
      out.write("  \r\n");
      out.write("	        </ol>\r\n");
      out.write("	\r\n");
      out.write("	      </li>\r\n");
      out.write("	      <li>\r\n");
      out.write("	        <h3>저자 소개</h3>\r\n");
      out.write("	        <p>");
      out.print(aIntro);
      out.write("</p>\r\n");
      out.write("	      </li>\r\n");
      out.write("	\r\n");
      out.write("	      <li class=\"one-review\">\r\n");
      out.write("	        <h3>한줄평</h3>\r\n");
      out.write("	        <div class=\"star-avg\">\r\n");
      out.write("	          <h4>평균<br />별점</h4>\r\n");
      out.write("	          <p>\r\n");
      out.write("	          	");

	          		for(int c=0; c<score; c++){//별생성
	          			
      out.write("\r\n");
      out.write("	          			<i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("	          			");

	          		}
	          		for(int e=0; e<5-score; e++){
	          			
      out.write("\r\n");
      out.write("	          			<i class=\"fa-regular fa-star\"></i>\r\n");
      out.write("	          			");

	          		}
	          	
      out.write("\r\n");
      out.write("	            ");
      out.print(score);
      out.write(".0 / 5.0\r\n");
      out.write("	            <i class=\"fa-solid fa-pencil\"></i>\r\n");
      out.write("	          </p>\r\n");
      out.write("	        </div><!--star-avg-->\r\n");
      out.write("	        <form name=\"reviewFrm\" method=\"post\">\r\n");
      out.write("	          <div class=\"input-star\">\r\n");
      out.write("	            <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("	            <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("	            <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("	            <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("	            <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("	          </div>\r\n");
      out.write("	          <input name=\"content\" id=\"content\" type=\"text\" max=\"70\"/>\r\n");
      out.write("	          <button type=\"button\" onclick=\"reviewFn()\">입력</button>\r\n");
      out.write("	          <input type=\"hidden\" name=\"bookid\" value=\"");
      out.print(bookid);
      out.write("\" />\r\n");
      out.write("	        </form>\r\n");
      out.write("	        <ul>\r\n");
      out.write("	        ");

	        	//한줄평 출력
	        	Vector<ReviewBean> rlist = null;
	        	rlist = bMgr.getReview(bookid);
	        	
	        	if(rlist.size() == 0){
	        		
      out.write("\r\n");
      out.write("	        		<li>등록된 한줄평이 없습니다.</li>\r\n");
      out.write("	        		");

	        	}else{
	        		
		        	for(int i=0; i<rlist.size(); i++){
		        		ReviewBean rbean = rlist.get(i);
		        		int rScore = rbean.getScore();
		        		String rContent = rbean.getContent();
		        		String nickname = rbean.getNickname();
		        		
      out.write("\r\n");
      out.write("		        		<li>     \r\n");
      out.write("		        		");

		        		for(int c=0; c<rScore; c++){//별 생성
		        			
      out.write("\r\n");
      out.write("		        			<i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("		        			");

		        		}//for - make colorstar
		        		for(int e=0; e<5-rScore; e++){
		        			
      out.write("\r\n");
      out.write("		        			<i class=\"fa-regular fa-star\"></i>\r\n");
      out.write("		        			");
 
		        		}//for - make emptystar
		        		
      out.write("\r\n");
      out.write("			        		<p>");
      out.print(rContent);
      out.write("</p>\r\n");
      out.write("			        		<span>");
      out.print(nickname);
      out.write("</span>\r\n");
      out.write("		        		</li>\r\n");
      out.write("		        		");

		        	}//for - li 
	        	}//else
	        
      out.write("\r\n");
      out.write("	         \r\n");
      out.write("	        </ul>\r\n");
      out.write("	      </li>\r\n");
      out.write("	    </ul>\r\n");
      out.write("	  </section>\r\n");
      out.write("	  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../components/footer.jsp", out, false);
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("<script>\r\n");
      out.write("//한줄평 별 호버시 색변화\r\n");
      out.write("	const $stars = document.querySelectorAll('.shop-product .input-star>i');\r\n");
      out.write("	let inputScore = 0;\r\n");
      out.write("	\r\n");
      out.write("	$stars.forEach(($star, idx)=>{\r\n");
      out.write("	  $star.addEventListener('mouseenter', ()=>{\r\n");
      out.write("	      for(let i=0; i<=idx; i++){\r\n");
      out.write("	      $stars[i].classList.add('colorstar');\r\n");
      out.write("	      }\r\n");
      out.write("	  });\r\n");
      out.write("	  $star.addEventListener('mouseleave', ()=>{\r\n");
      out.write("	    for(let i=0; i<$stars.length; i++){\r\n");
      out.write("	      $stars[i].classList.remove('colorstar');\r\n");
      out.write("	    }\r\n");
      out.write("	  });\r\n");
      out.write("	\r\n");
      out.write("	  //해당 별점 - 클릭이벤트\r\n");
      out.write("	  $star.addEventListener('click', ()=>{\r\n");
      out.write("	    for(let i=0; i<=idx; i++){\r\n");
      out.write("	      $stars[i].style.color = 'rgb(100, 130, 173)';/******* 포인트 컬러에 따라 변경 필요********/\r\n");
      out.write("	    }\r\n");
      out.write("	    for(let k=$stars.length-1; k>idx; k--){\r\n");
      out.write("	      $stars[k].style.color = '#ddd';/******* 포인트 컬러에 따라 변경 필요********/\r\n");
      out.write("	    }\r\n");
      out.write("	    inputScore = idx+1;\r\n");
      out.write("	  });\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	//한줄평 등록 확인창\r\n");
      out.write("	const userid = '");
      out.print(userid);
      out.write("';\r\n");
      out.write("	const frm = document.reviewFrm;\r\n");
      out.write("\r\n");
      out.write("	const checkReview = () => {\r\n");
      out.write("		\r\n");
      out.write("	  //쿼리스트링으로 JS에서 클릭했던 별점 inputScore 값 보내줌\r\n");
      out.write("	  const url = '/shop/shop03?inputScore='+ inputScore + '&idKey=");
      out.print(userid);
      out.write("';\r\n");
      out.write("	  window.open(url, \"review\", \"width=400, height=300\");\r\n");
      out.write("	  frm.action = url;\r\n");
      out.write("	  frm.target = \"review\";\r\n");
      out.write("	  frm.submit();\r\n");
      out.write("	};\r\n");
      out.write("	\r\n");
      out.write("	const reviewFn = () => {\r\n");
      out.write("		//유효성 검사\r\n");
      out.write("		if(frm.content.value == ''){\r\n");
      out.write("			alert('한줄평 내용을 입력해 주세요.');\r\n");
      out.write("			document.frm.content.focus();\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("	\r\n");
      out.write("		if(userid === '0'){//비로그인 상태\r\n");
      out.write("			const loginAnswer = confirm('로그인해야 이용가능한 서비스입니다. 로그인 하시겠습니까?');\r\n");
      out.write("\r\n");
      out.write("			if(loginAnswer){\r\n");
      out.write("				location.href = '/login/login01';\r\n");
      out.write("			}\r\n");
      out.write("		} else{\r\n");
      out.write("			checkReview();\r\n");
      out.write("		}\r\n");
      out.write("	}//reviewFn()\r\n");
      out.write("	\r\n");
      out.write("    \r\n");
      out.write("	//로그인 상태 확인 - 팝업창/shopProc이동\r\n");
      out.write("	makePopup = (save) => {\r\n");
      out.write("		\r\n");
      out.write("	    const popupWidth = 500;\r\n");
      out.write("	    const popupHeight = 350;\r\n");
      out.write("	    //팝업창 중앙 배치\r\n");
      out.write("	    let popupLeft = (window.screen.width / 2) - (popupWidth / 2);\r\n");
      out.write("	    let popupTop = (window.screen.height / 2) - (popupHeight / 2);\r\n");
      out.write("		\r\n");
      out.write("	    if (userid === '0') {\r\n");
      out.write("	        //비로그인 상태일 경우 팝업창 생성\r\n");
      out.write("	        const url = '/buy/buy02';\r\n");
      out.write("	        window.open(url, 'checkMember', 'width='+ popupHeight + ', height=' + popupHeight + ', left=' + popupLeft + ', top=' + popupTop);\r\n");
      out.write("	    }else{\r\n");
      out.write("	    	//장바구니/관심목록 구분\r\n");
      out.write("			if(save==='cart'){\r\n");
      out.write("				document.orderFrm.action = '/procs/shopProc?save=cart';\r\n");
      out.write("			}else if(save==='wish'){\r\n");
      out.write("				document.orderFrm.action = '/procs/shopProc?save=wish';\r\n");
      out.write("			}else{\r\n");
      out.write("				document.orderFrm.action = '/buy/buy01';\r\n");
      out.write("			}\r\n");
      out.write("		    document.orderFrm.submit();\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("	//바로 구매 클릭시\r\n");
      out.write("    const toBuy = (event) => {\r\n");
      out.write("	    event.preventDefault();\r\n");
      out.write("	    makePopup('buy');\r\n");
      out.write("\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("    //관심목록 클릭시\r\n");
      out.write("	const toWish = (event) => {\r\n");
      out.write("	    event.preventDefault();\r\n");
      out.write("	    makePopup('wish');\r\n");
      out.write("\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	//장바구니 클릭시\r\n");
      out.write("	const toCart = (event) => {\r\n");
      out.write("		event.preventDefault();\r\n");
      out.write("		makePopup('cart');\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
