/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.96
 * Generated at: 2024-12-06 07:28:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.choice;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import beans.BookBean;

public final class choice01_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("beans.BookBean");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      book.BookInfoMgr bMgr = null;
      bMgr = (book.BookInfoMgr) _jspx_page_context.getAttribute("bMgr", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (bMgr == null){
        bMgr = new book.BookInfoMgr();
        _jspx_page_context.setAttribute("bMgr", bMgr, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      book.BookOrderMgr oMgr = null;
      oMgr = (book.BookOrderMgr) _jspx_page_context.getAttribute("oMgr", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (oMgr == null){
        oMgr = new book.BookOrderMgr();
        _jspx_page_context.setAttribute("oMgr", oMgr, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');
 
	request.setCharacterEncoding("UTF-8");
	
	//로그인 상태 확인
	int userid = 0; 
	
	if(session.getAttribute("idKey") !=null){
		//세션값 int로 저장 
		Object sessionValue = session.getAttribute("idKey");
			
		// 타입 확인 후 변환
		if (sessionValue instanceof String) {
		    String strValue = (String) sessionValue; // String으로 캐스팅
		    try {
		        userid = Integer.parseInt(strValue);
		    } catch (NumberFormatException e) {
		        e.printStackTrace(); // 변환 실패 시 예외 처리
		    }
		} else if (sessionValue instanceof Integer) {
		    // 만약 세션에 직접 Integer로 저장되어 있다면
		    userid = (Integer) sessionValue; 
		} 
	} 

	Vector<BookBean> vlist = null;

	//1~87 범위안의 무작위 수 4개 -> 추천할 bookid
	Random r = new Random();
	ArrayList<Integer> list = new ArrayList();
	for(int i=0; i<4; i++){ 
		int number=r.nextInt(87)+1; 
		if(!list.contains(number)){
			list.add(number); 
			}else{ 
				i--;
			} 	
		} 
	
	//무작위 수 4개 slist에 저장하고 id로 제목 끌어오기 
	ArrayList<String> slist = new ArrayList();

	for(int i=0; i<list.size(); i++){ 
		vlist=bMgr.getBook(list.get(i)); 
		BookBean bean = vlist.get(0); 
		String tit=bean.getTitle();
		slist.add(tit); 
	} 

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("	<meta charset=\"UTF-8\" />\r\n");
      out.write("	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/reset.css?after\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/index.css?after\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/choice01.css?after\" />\r\n");
      out.write("<title>추천 도서 페이지</title>\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/9698826605.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script defer src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/choice01.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<div id=\"wrap\">\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../components/header.jsp", out, false);
      out.write("\r\n");
      out.write("		<section class=\"choice\">\r\n");
      out.write("			<h2>\r\n");
      out.write("				<i class=\"fa-solid fa-star-and-crescent\"></i>\r\n");
      out.write("				추천 오로라\r\n");
      out.write("			</h2>\r\n");
      out.write("			<nav>\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li class=\"on\"><a href=\"#\">\r\n");
      out.write("							");
      out.print(slist.get(0));
      out.write("\r\n");
      out.write("						</a></li>\r\n");
      out.write("					<li><a href=\"#\">\r\n");
      out.write("							");
      out.print(slist.get(1));
      out.write("\r\n");
      out.write("						</a></li>\r\n");
      out.write("					<li><a href=\"#\">\r\n");
      out.write("							");
      out.print(slist.get(2));
      out.write("\r\n");
      out.write("						</a></li>\r\n");
      out.write("					<li><a href=\"#\">\r\n");
      out.write("							");
      out.print(slist.get(3));
      out.write("\r\n");
      out.write("						</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</nav>\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"frame\">\r\n");
      out.write("					<a href=\"#\"><i class=\"fa-solid fa-circle-chevron-left\"></i></a>\r\n");
      out.write("					<a href=\"#\"><i class=\"fa-solid fa-circle-chevron-right\"></i></a>\r\n");
      out.write("					<div class=\"slide-recommend\">\r\n");
      out.write("						");
 
							for(int i=0; i<list.size(); i++){ 
								int bookid = list.get(i); 
								String imgUrl = "/image?bookid="+bookid; 
								vlist = bMgr.getBook(bookid); 
								BookBean bean = vlist.get(0); 
								String tit = bean.getTitle(); 
								String author = bean.getAuthor(); 
								String category = bean.getCategory();
								String genre = bean.getGenre(); 
								String mini = bean.getMiniIntro(); 
								String review = bean.getReview();
								String contents = bean.getContents(); 
						
      out.write("\r\n");
      out.write("						<article>\r\n");
      out.write("							<h3>\r\n");
      out.write("								");
      out.print(tit);
      out.write("\r\n");
      out.write("							</h3>\r\n");
      out.write("							<p>지은이 - ");
      out.print(author);
      out.write(" &dot; ");
      out.print(category);
      out.write(' ');
      out.write('/');
      out.write(' ');
      out.print(genre);
      out.write("\r\n");
      out.write("							</p>\r\n");
      out.write("							<h4>\"");
      out.print(mini);
      out.write("\"</h4>\r\n");
      out.write("							<img src=\"");
      out.print(imgUrl);
      out.write("\" alt=\"");
      out.print(tit);
      out.write("\">\r\n");
      out.write("							<div>\r\n");
      out.write("								<a href=\"/shop/shop02?bookid=");
      out.print(bookid);
      out.write("\"><i\r\n");
      out.write("										class=\"fa-solid fa-magnifying-glass\"></i></a>\r\n");
      out.write("								<a href=\"/mypage/mypage05\" onclick=\"toCart(event, ");
      out.print(bookid);
      out.write(")\"><i\r\n");
      out.write("										class=\"fa-solid fa-cart-shopping\"></i></a>\r\n");
      out.write("								<a href=\"/mypage/mypage05\" onclick=\"toWish(event, ");
      out.print(bookid);
      out.write(")\"><i\r\n");
      out.write("										class=\"fa-solid fa-heart-circle-plus\"></i></a>\r\n");
      out.write("							</div>\r\n");
      out.write("							<h5>독자의 한 마디</h5>\r\n");
      out.write("							<p>\r\n");
      out.write("								");
      out.print(review);
      out.write("!\r\n");
      out.write("							</p>\r\n");
      out.write("							<h5>책속에서</h5>\r\n");
      out.write("							<p>\r\n");
      out.write("								");
      out.print(contents);
      out.write("\r\n");
      out.write("							</p>\r\n");
      out.write("						</article>\r\n");
      out.write("		\r\n");
      out.write("						");
 }//for 
      out.write("\r\n");
      out.write("								 \r\n");
      out.write("			       \r\n");
      out.write("					</div>\r\n");
      out.write("				</div><!--.frame-->\r\n");
      out.write("			</div><!--.container-->\r\n");
      out.write("		</section>\r\n");
      out.write("\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../components/footer.jsp", out, false);
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("<script>\r\n");
      out.write("	//로그인 상태 확인 - 팝업창 생성\r\n");
      out.write("	const userid = '");
      out.print(userid);
      out.write("';\r\n");
      out.write("	\r\n");
      out.write("	const makePopup = (save, bookid) => {\r\n");
      out.write("	   \r\n");
      out.write("	    const popupWidth = 500;\r\n");
      out.write("	    const popupHeight = 350;\r\n");
      out.write("	    let popupLeft = (window.screen.width / 2) - (popupWidth / 2);\r\n");
      out.write("	    let popupTop = (window.screen.height / 2) - (popupHeight / 2);\r\n");
      out.write("	\r\n");
      out.write("	    if (userid === '0') {\r\n");
      out.write("	        //비로그인 상태일 경우 팝업창 생성\r\n");
      out.write("	        const url = '/buy/buy02';\r\n");
      out.write("	        window.open(url, 'checkMember', 'width='+ popupHeight + ', height=' + popupHeight + ', left=' + popupLeft + ', top=' + popupTop);\r\n");
      out.write("	    }else{\r\n");
      out.write("	    	//장바구니/관심목록 구분\r\n");
      out.write("			if(save === 'cart'){\r\n");
      out.write("				location.href = '/shop/shopProc?orderNum=1&save=cart&bookid=' + bookid;\r\n");
      out.write("			}else if(save==='wish'){\r\n");
      out.write("				location.href = '/shop/shopProc?orderNum=1&save=wish&bookid=' + bookid;\r\n");
      out.write("			}else{\r\n");
      out.write("				document.orderFrm.action = '/buy/buy01?orderNum=1&save=buy&bookid=' + bookid;\r\n");
      out.write("			}\r\n");
      out.write("	    }\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("	const toBuy = (evt, bookid) => {\r\n");
      out.write("		evt.preventDefault();\r\n");
      out.write("		makePopup('buy',bookid);\r\n");
      out.write("	}\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("	const toWish = (evt, bookid) => {\r\n");
      out.write("		evt.preventDefault();\r\n");
      out.write("		makePopup('wish',bookid);\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	const toCart = (evt, bookid) => {\r\n");
      out.write("		evt.preventDefault();\r\n");
      out.write("		makePopup('cart', bookid);\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
