/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.96
 * Generated at: 2024-11-15 06:51:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import beans.MemberBean;
import beans.BookBean;

public final class board04_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("beans.BookBean");
    _jspx_imports_classes.add("beans.MemberBean");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      board.BoardMgr bMgr = null;
      bMgr = (board.BoardMgr) _jspx_page_context.getAttribute("bMgr", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (bMgr == null){
        bMgr = new board.BoardMgr();
        _jspx_page_context.setAttribute("bMgr", bMgr, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write("\r\n");
      out.write("<!-- 글작성 페이지 -->\r\n");

	request.setCharacterEncoding("UTF-8");
	Integer loginId = null;
	String loginNickname = null;
	
	if(session != null && session.getAttribute("idKey") != null) {
		loginId = (Integer)session.getAttribute("idKey");
		loginNickname = bMgr.getNickname(loginId);
	}
	
	// 로그인유무로 접근제한 하기 위한 boolean값
	boolean loginOk = (session != null && loginId != null);
	String category = request.getParameter("category");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("  <title>글쓰기 | 은하수책방</title>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/reset copy 2.css?after\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/board.css?after\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css\">\r\n");
      out.write("  <script defer src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/header.js\"></script>\r\n");
      out.write("  <script defer src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/board04.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  <div id=\"wrap\">\r\n");
      out.write("   \r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../components/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <section>\r\n");
      out.write("      <h2><a href=\"board01\">은하수 광장✨</a></h2>\r\n");
      out.write("      <form action=\"boardPost\" method=\"post\" name=\"FrmPost\" id=\"FrmPost\" enctype=\"multipart/form-data\" autocomplete=\"off\">\r\n");
      out.write("      	<input type=\"hidden\" name=\"userid\" value=\"");
      out.print(loginId);
      out.write("\" />\r\n");
      out.write("      	<input type=\"hidden\" name=\"nickname\" value=\"");
      out.print(loginNickname);
      out.write("\" />\r\n");
      out.write("		<input type=\"hidden\" name=\"userip\" value=\"");
      out.print(request.getRemoteAddr());
      out.write("\" />\r\n");
      out.write("		<input type=\"hidden\" name=\"category\" value=\"");
      out.print(category);
      out.write("\" />\r\n");
      out.write("        <div id=\"writeArea\">\r\n");
      out.write("          <select name=\"postGenre\" id=\"postGenre\" required>\r\n");
      out.write("	          \r\n");
      out.write("	        <!-- 카테고리목록 출력 -->\r\n");
      out.write("	        ");
  ArrayList<String> cList = bMgr.getCategoryList();
        		// 넘어온 카테고리와 옵션값이 같은것에 seleted || 전체일경우 '카테고리 선택' 표시
		        if(category.equals("전체")) {
      out.write("\r\n");
      out.write("	          	<option value=\"\" selected disabled hidden>카테고리 선택</option>\r\n");
      out.write("	         ");
 }
	        	for(int i=1; i<cList.size(); i++) {	
      out.write("\r\n");
      out.write("	           	<option value=\"");
      out.print(cList.get(i));
      out.write('"');
      out.write(' ');
 if(cList.get(i).equals(category)) {
      out.write(" selected ");
}
      out.write(' ');
      out.write('>');
      out.print(cList.get(i));
      out.write("</option>\r\n");
      out.write("	        ");
 } 
      out.write("\r\n");
      out.write("          </select>\r\n");
      out.write("          \r\n");
      out.write("          <div id=\"writeHead\">\r\n");
      out.write("            <select name=\"postTab\" id=\"postTab\">\r\n");
      out.write("            <!-- 탭테이블의 0,1,2 항목은 전체,인기,일반 고정 -->\r\n");
      out.write("              <option value=\"일반\" selected>일반</option>\r\n");
      out.write("            <!-- 카테고리목록 출력 -->\r\n");
      out.write("	        ");
  ArrayList<String> tList = bMgr.getTabList();
	        	for(int i=3; i<tList.size(); i++) {
      out.write("\r\n");
      out.write("	           	<option value=\"");
      out.print(tList.get(i));
      out.write('"');
      out.write('>');
      out.print(tList.get(i));
      out.write("</option>\r\n");
      out.write("	        ");
 } 
      out.write("\r\n");
      out.write("            </select>\r\n");
      out.write("  \r\n");
      out.write("            <input type=\"text\" name=\"postTit\" placeholder=\"제목을 입력해 주세요.\" />\r\n");
      out.write("          </div>\r\n");
      out.write("  \r\n");
      out.write("          <div id=\"postEditor\">\r\n");
      out.write("            <textarea name=\"postCont\"></textarea>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div id=\"uploadArea\">\r\n");
      out.write("          <h3>첨부파일</h3>\r\n");
      out.write("\r\n");
      out.write("          <div id=\"upload\">\r\n");
      out.write("            <ul id=\"uploadName\">\r\n");
      out.write("              <li>선택된 파일이 없습니다.</li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <label for=\"uploadFile\">파일찾기</label>\r\n");
      out.write("            <input type=\"file\" name=\"uploadFile\" id=\"uploadFile\" accept=\"image/*\" />\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div id=\"bookSearchArea\">\r\n");
      out.write("          <h3>연관도서</h3>\r\n");
      out.write("		  <div id=\"selectedBook\" onclick=\"postBookFn()\">🔍 이 책에 대해 이야기하고 계신가요?</div>\r\n");
      out.write("		  <input type=\"hidden\" id=\"postBook\" name=\"postBook\" />\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("        <div id=\"postBtn\">\r\n");
      out.write("          <button type=\"button\" onclick=\"cancelChk()\">목록</button>\r\n");
      out.write("          <button type=\"button\" onclick=\"writeChk()\">작성</button>\r\n");
      out.write("        </div>\r\n");
      out.write("      </form>\r\n");
      out.write("      \r\n");
      out.write("      <div id=\"postBookFrm\">\r\n");
      out.write("      	<div id=\"formHead\">\r\n");
      out.write("	      	<h4>도서 검색</h4>\r\n");
      out.write("	      	<i class=\"fa-solid fa-xmark\" onclick=\"postBookFn()\"></i>\r\n");
      out.write("      	</div>\r\n");
      out.write("      	\r\n");
      out.write("      	<input onkeyup=\"if(window.event.keyCode==13){(postBookSearchFn())}\" id=\"postBookSearch\" placeholder=\"도서명 & 작가명으로 검색해보세요\" autocomplete=\"off\" />\r\n");
      out.write("      	<ul id=\"bookSearchList\">\r\n");
      out.write("   		");

   		String keyword = " ";
   		ArrayList<BookBean> bList = bMgr.getSearchBookList(keyword);
   		// 추출된 책이 있을경우
		  if(!bList.isEmpty()) {
		  	for(int i=0; i<bList.size(); i++) { 
				BookBean bean = bList.get(i); 
      out.write("\r\n");
      out.write("		   		<li onclick=\"bookSelectFn(");
      out.print(bean.getBookid());
      out.write(',');
      out.write(' ');
      out.write('\'');
      out.print(bean.getTitle());
      out.write("', '");
      out.print(bean.getAuthor());
      out.write("')\">\r\n");
      out.write("		   			<div>\r\n");
      out.write("			   			<span>");
      out.print( bean.getTitle() );
      out.write("</span>\r\n");
      out.write("			   			<span>");
      out.print( bean.getAuthor() );
      out.write("</span>\r\n");
      out.write("		   			</div>\r\n");
      out.write("		   			");
 // 첨부이미지가 있으면 출력
		   			if(bean.getPhoto() != null) { 
      out.write("\r\n");
      out.write("		   			<img src=\"data:image/jpeg;base64, ");
      out.print( java.util.Base64.getEncoder().encodeToString(bean.getPhoto()) );
      out.write("\" alt=\"");
      out.print( bean.getTitle() );
      out.write("\">\r\n");
      out.write("	   			 ");
 } else { 
      out.write("\r\n");
      out.write("	   				<img src=\"https://upload.wikimedia.org/wikipedia/commons/6/65/No-Image-Placeholder.svg\" alt=\"");
      out.print( bean.getTitle() );
      out.write("\">\r\n");
      out.write("	   			 ");
 } 
      out.write("\r\n");
      out.write("		   		</li>\r\n");
      out.write("	 		");
 } 
      out.write("\r\n");
      out.write("	   	");
 } 
      out.write("\r\n");
      out.write("      	</ul>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <footer>\r\n");
      out.write("      푸터영역\r\n");
      out.write("    </footer>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <script>\r\n");
      out.write("	// 페이지 로드 시, 로그인이 안되어있으면 confirm (직접 주소창으로 접근 시 제한)\r\n");
      out.write("	window.onload = function() {\r\n");
      out.write("      if(");
      out.print(!loginOk);
      out.write(") {\r\n");
      out.write("         const result = confirm(\"로그인이 필요한 서비스 입니다.\\n로그인 하시겠습니까?\")\r\n");
      out.write("         if(result) {\r\n");
      out.write("            location.href = \"../login/login01\";\r\n");
      out.write("         } else {\r\n");
      out.write("            location.href = \"board01\";\r\n");
      out.write("         }\r\n");
      out.write("      }\r\n");
      out.write(" 	};\r\n");
      out.write("  \r\n");
      out.write("  	// 목록보기 버튼\r\n");
      out.write("  	function cancelChk() {\r\n");
      out.write("  		const result = confirm(\"작성 중인 내용은 삭제됩니다.\\n글 작성을 취소하고 목록으로 돌아가시겠습니까?\");\r\n");
      out.write("  		if(result) {\r\n");
      out.write("  			location.href = \"board01\";\r\n");
      out.write("  		}\r\n");
      out.write("  	}\r\n");
      out.write("  \r\n");
      out.write("  	// 글작성 버튼 - 유효성검사 후 submit\r\n");
      out.write("    function writeChk() {\r\n");
      out.write("      const $frm = document.FrmPost;\r\n");
      out.write("\r\n");
      out.write("      if($frm.postGenre.value == \"\") {\r\n");
      out.write("        alert(\"카테고리를 선택해주세요.\");\r\n");
      out.write("        $frm.postGenre.focus();\r\n");
      out.write("        return;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      if($frm.postTit.value == null || $frm.postTit.value == \"\") {\r\n");
      out.write("        alert(\"제목을 입력해주세요.\");\r\n");
      out.write("        $frm.postTit.focus();\r\n");
      out.write("        return;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      if($frm.postCont.value == null || $frm.postCont.value == \"\") {\r\n");
      out.write("        alert(\"내용을 입력해주세요.\");\r\n");
      out.write("        $frm.postCont.focus();\r\n");
      out.write("        return;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("   	  // 비로그인 유저 권한 없음\r\n");
      out.write("      if(!");
      out.print(loginOk);
      out.write(") {\r\n");
      out.write("    	alert(\"권한이 없습니다.\");\r\n");
      out.write("		location.href = \"board01\";\r\n");
      out.write("      }\r\n");
      out.write("   \r\n");
      out.write("      $frm.submit();\r\n");
      out.write("      \r\n");
      out.write("    }\r\n");
      out.write("  	\r\n");
      out.write("  </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
