/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.96
 * Generated at: 2024-11-15 06:53:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import board.BoardMgr;
import beans.BookBean;
import java.util.ArrayList;

public final class boardBookSearch_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("beans.BookBean");
    _jspx_imports_classes.add("board.BoardMgr");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	ArrayList<BookBean> bList = (ArrayList<BookBean>)request.getAttribute("bList");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div id=\"formHead\">\r\n");
      out.write("      	<h4>도서 검색</h4>\r\n");
      out.write("      	<i class=\"fa-solid fa-xmark\" onclick=\"postBookFn()\"></i>\r\n");
      out.write("   	</div>\r\n");
      out.write("     	\r\n");
      out.write("   	<input onkeyup=\"if(window.event.keyCode==13){(postBookSearchFn())}\" id=\"postBookSearch\" placeholder=\"도서명 & 작가명으로 검색해보세요\" autocomplete=\"off\" />\r\n");
      out.write("	<ul id=\"bookSearchList\">\r\n");
      out.write("	");
 // 추출된 책이 있을경우
	  if(!bList.isEmpty()) {
	  	for(int i=0; i<bList.size(); i++) { 
			BookBean bean = bList.get(i); 
      out.write("\r\n");
      out.write("	   		<li onclick=\"bookSelectFn(");
      out.print(bean.getBookid());
      out.write(',');
      out.write(' ');
      out.write('\'');
      out.print(bean.getTitle());
      out.write("', '");
      out.print(bean.getAuthor());
      out.write("')\">\r\n");
      out.write("		   			<div>\r\n");
      out.write("			   			<span>");
      out.print( bean.getTitle() );
      out.write("</span>\r\n");
      out.write("			   			<span>");
      out.print( bean.getAuthor() );
      out.write("</span>\r\n");
      out.write("		   			</div>\r\n");
      out.write("		   			");
 // 첨부이미지가 있으면 출력
	                if(bean.getPhoto() != null) { 
      out.write("\r\n");
      out.write("		   			<img src=\"data:image/jpeg;base64, ");
      out.print( java.util.Base64.getEncoder().encodeToString(bean.getPhoto()) );
      out.write("\" alt=\"");
      out.print( bean.getTitle() );
      out.write("\">\r\n");
      out.write("	   			 ");
 } else { 
      out.write("\r\n");
      out.write("	   				<img src=\"https://upload.wikimedia.org/wikipedia/commons/6/65/No-Image-Placeholder.svg\" alt=\"");
      out.print( bean.getTitle() );
      out.write("\">\r\n");
      out.write("	   			 ");
 } 
      out.write("\r\n");
      out.write("		   		</li>\r\n");
      out.write(" 		");
 } 
      out.write("\r\n");
      out.write("   	");
 } 
      out.write("\r\n");
      out.write("   	</ul>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
