/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.96
 * Generated at: 2024-11-15 12:35:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import beans.BoardBean;
import beans.CommentBean;
import beans.MemberBean;

public final class commentBox_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(6);
    _jspx_imports_classes.add("beans.CommentBean");
    _jspx_imports_classes.add("beans.MemberBean");
    _jspx_imports_classes.add("beans.BoardBean");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      board.BoardMgr bMgr = null;
      bMgr = (board.BoardMgr) _jspx_page_context.getAttribute("bMgr", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (bMgr == null){
        bMgr = new board.BoardMgr();
        _jspx_page_context.setAttribute("bMgr", bMgr, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');

	request.setCharacterEncoding("UTF-8");

	// 서블릿 req에서 필요한 데이터 추출
	int num = (int)request.getAttribute("boardid");	
	int postuser = (int)request.getAttribute("postuser");
	
	Integer loginId = null;
	String loginNickname = null;
	
	// 로그인 상태면 필요한 데이터 추출(id, nickname)
	if(session != null && session.getAttribute("idKey") != null) {
		loginId = (Integer)session.getAttribute("idKey");
		loginNickname = bMgr.getNickname(loginId);
	}
	
	// 댓글 페이징
	int totalRecord=0; //전체레코드수
	int numPerPage=10; // 페이지당 레코드 수 
	int pagePerBlock=5; //블럭당 페이지수 
	int totalPage=0; //전체 페이지 수
	int totalBlock=0;  //전체 블럭수
	int nowPage=1; // 현재페이지
	int nowBlock=1;  //현재블럭
	int start=0; //디비의 select 시작번호
	int end=numPerPage; //시작번호로 부터 가져올 select 갯수
	int listSize=0; // DB로부터 추출해 list에 저장한 댓글 수
	
	// 페이징, 글목록출력 등에 활용될 변수 초기화 (총게시글수, 총페이지수, 현재블럭, 총블럭수)
	totalRecord = (int)request.getAttribute("commentCount");
	totalPage = (int)Math.ceil((double)totalRecord / numPerPage);  //전체페이지수
	nowBlock = (int)Math.ceil((double)nowPage/pagePerBlock); //현재블럭 계산
	totalBlock = (int)Math.ceil((double)totalPage / pagePerBlock);  //전체블럭계산
	
	// 페이지네이션 초기화
	if(request.getAttribute("nowBlock") != null) {
		nowBlock = (int)request.getAttribute("nowBlock");    		
	}
	// 현재 블럭에서의 시작번호 (현재블럭과 블럭당페이지수로 계산)
	int pageStart = (nowBlock-1)*pagePerBlock+1;
    if(request.getAttribute("pageStart") != null) {
    	pageStart = (int)request.getAttribute("pageStart");
    }
	
    // 현재 블럭에서의 끝번호 ()
   	int pageEnd = ((pageStart + pagePerBlock ) <= totalPage) ?  (pageStart + pagePerBlock): totalPage+1;
	if(request.getAttribute("pageEnd") != null) {
        pageEnd = (int)request.getAttribute("pageEnd");    		
	}
	
	if(request.getAttribute("nowPage") != null) {
		nowPage = (int)request.getAttribute("nowPage");    		
	}
	
	// 페이지이동 시 게시글을 DB에서 추출할 때 기준이 되는 값을 초기화
	start = (nowPage-1)*numPerPage;
	if(request.getAttribute("start") != null) {
		start = (int)request.getAttribute("start");    		
	}
	end = numPerPage;
	if(request.getAttribute("end") != null) {
		end = (int)request.getAttribute("end");    		
	}
	//start = ((nowPage-1)*numPerPage)+bMgr.getTotalPrevDelCount(num, nowPage, numPerPage);
	//end = numPerPage+bMgr.getDeleteComCount(num, start, numPerPage);
	
	int commentCount = (int)request.getAttribute("commentCount");
	ArrayList<CommentBean> clist = (ArrayList<CommentBean>)request.getAttribute("clist");
	
	int activeComCount = bMgr.getActiveComCount(num);

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>게시물 댓글</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/reset copy 2.css?after\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/board.css?after\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css\">\r\n");
      out.write("<script defer src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/header.js\"></script>\r\n");
      out.write("<script defer src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/board02.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div id=\"commentHead\">\r\n");
      out.write("	        <div id=\"commentOpt\">\r\n");
      out.write("	          <h3>댓글 [<span>");
      out.print( activeComCount );
      out.write("</span>]</h3>\r\n");
      out.write("	          <select name=\"commentSort\" id=\"commentSort\">\r\n");
      out.write("	            <option value=\"등록순\">등록순</option>\r\n");
      out.write("	            <option value=\"최신순\">최신순</option>\r\n");
      out.write("	          </select>\r\n");
      out.write("	        </div> <!-- div#commentOpt -->\r\n");
      out.write("	\r\n");
      out.write("	        <div id=\"commentMng\">\r\n");
      out.write("	          <span onclick=\"window.scrollTo({ top: 0, behavior: 'smooth' });\">본문보기</span>\r\n");
      out.write("	        </div> <!-- div#commentMng -->\r\n");
      out.write("      </div> <!--commentHead-->\r\n");
      out.write("	\r\n");
      out.write("      ");
 listSize = clist.size();
         
         // 반복문으로 출력할 댓글이 한페이지댓글수 보다 많으면 그만큼만,
         // 그보다 적으면 가진만큼만 반복
         int forCount = 0;
         if(listSize >= numPerPage) {forCount = numPerPage;}
         else {forCount = listSize;}
         
      out.write("\r\n");
      out.write("	\r\n");
      out.write("     	<div id=\"commentCont\"> \r\n");
      out.write("		");
// 추출된 댓글이 있을경우
         if(!clist.isEmpty()) { 
      out.write("\r\n");
      out.write("		  ");
 for(int i=0; i<forCount; i++) {
				CommentBean bean = clist.get(i);
				int commentId = bean.getCommentid();
				String comNickname = bean.getNickname();
				String comRegdate = bean.getRegdate();
				String comContent = bean.getContent();
				int comUserid = bean.getUserid();
				int comPos = bean.getPos();
				int comDepth = bean.getDepth();
				int comStatus = bean.getStatus();
				String comUpdate = bean.getUpdateDate();
				
				//status==0인건 정상출력/status=9면서 대댓이있는건 내용대체출력+버튼미출력
				// 만약 depth가 있으면 class에 depth-뎁스값 부여
		        if(comStatus==0) { 
      out.write("\r\n");
      out.write("	    	<div class=\"comment comment-");
      out.print(num);
      out.write(" comid-");
      out.print(commentId);
      out.write("\r\n");
      out.write("	    		");
if(comDepth > 0) {
      out.write(" depth depth-");
      out.print(comDepth);
      out.write("\"\r\n");
      out.write("	    		");
 int depthPx = comDepth <= 16 ?  (30 * comDepth) : (30 * 16); 
      out.write("\r\n");
      out.write("	    		style=\"margin-left: ");
      out.print(depthPx);
}
      out.write("px;\">\r\n");
      out.write("	    	\r\n");
      out.write("	          <div class=\"commentInfo\">\r\n");
      out.write("	            <div class=\"authorInfo\">\r\n");
      out.write("		            ");
 // 글작성자와 댓글작성자가 같을경우 작성자표시
		           		if(postuser == comUserid) {
      out.write("\r\n");
      out.write("		            	<span class=\"commentAuthor same\">\r\n");
      out.write("		           ");
 } else { 
      out.write("\r\n");
      out.write("		            	<span class=\"commentAuthor\">\r\n");
      out.write("		         	 ");
 } 
      out.write("\r\n");
      out.write("		            ");
      out.print(comNickname);
      out.write("</span>\r\n");
      out.write("		            \r\n");
      out.write("		            ");
 // 업데이트일이 존재할 시 (수정됨) 출력
		            	if(comUpdate != null) { 
      out.write("\r\n");
      out.write("		            	<span class=\"comUpdate\">(수정됨)</span>\r\n");
      out.write("		            ");
 } 
      out.write("\r\n");
      out.write("          	</div> <!-- .authorInfo -->\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"commentAdd\">\r\n");
      out.write("              <span class=\"commentDate\">");
      out.print(comRegdate);
      out.write("</span>\r\n");
      out.write("              \r\n");
      out.write("           	");
 // 로그인 시에만 답글버튼
			if(loginId != null) { 
      out.write("\r\n");
      out.write("              <div class=\"author-addOns\">\r\n");
      out.write("              	<span onclick=\"toggleReply(this);\"><i class=\"fa-solid fa-reply\" title=\"답글\"></i></span>\r\n");
      out.write("			 \r\n");
      out.write("             ");
 // 내댓글일 때만 수정/삭제버튼
				if(comUserid == loginId) {
      out.write("\r\n");
      out.write("                <span onclick=\"toggleEdit(this);\"><i class=\"fa-solid fa-pencil\" title=\"댓글수정\"></i></span>\r\n");
      out.write("                <span onclick=\"commentDelete(");
      out.print(commentId);
      out.write(',');
      out.write(' ');
      out.print(loginId);
      out.write(',');
      out.write(' ');
      out.print(comPos);
      out.write(',');
      out.write(' ');
      out.print(num);
      out.write(',');
      out.write(' ');
      out.print(end);
      out.write(',');
      out.write(' ');
      out.print(comUserid);
      out.write(',');
      out.write(' ');
      out.print(nowBlock);
      out.write(',');
      out.write(' ');
      out.print(nowPage);
      out.write(',');
      out.write(' ');
      out.print(pagePerBlock);
      out.write(',');
      out.write(' ');
      out.print(totalPage);
      out.write(");\"><i class=\"fa-solid fa-trash-can\" title=\"댓글삭제\"></i></span>\r\n");
      out.write("             ");
 } 
      out.write("\r\n");
      out.write("              </div> <!-- .author-addOns -->\r\n");
      out.write("         ");
 } //if(loginId != null) 
      out.write("\r\n");
      out.write("            </div> <!-- commentAdd -->\r\n");
      out.write("            \r\n");
      out.write("          </div> <!-- commentInfo -->\r\n");
      out.write("          \r\n");
      out.write("          <div class=\"commentMsg\">\r\n");
      out.write("            <p class=\"text\">");
      out.print(comContent);
      out.write("</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div> <!-- .comment -->\r\n");
      out.write("        \r\n");
      out.write("        <!-- 댓글수정 폼 (숨김/수정버튼으로 토글) -->\r\n");
      out.write("        <form action=\"commentEdit\" name=\"comEditFrm\" id=\"comEditFrm\" method=\"post\" autocomplete=\"off\" class=\"off\">\r\n");
      out.write("	        <div id=\"writeComment\">\r\n");
      out.write("	          <p class=\"commentAuthor\">\r\n");
      out.write("	            <span>수정</span>");
      out.print(loginNickname);
      out.write("\r\n");
      out.write("	          </p>\r\n");
      out.write("	          <textarea name=\"inputComment\" placeholder=\"댓글을 작성해보세요!\">");
      out.print(comContent);
      out.write("</textarea>\r\n");
      out.write("	          <button type=\"button\" onclick=\"editSubmit(");
      out.print(commentId);
      out.write(',');
      out.write(' ');
      out.print(loginId);
      out.write(',');
      out.write(' ');
      out.write('\'');
      out.print(loginNickname);
      out.write('\'');
      out.write(',');
      out.write(' ');
      out.print(num);
      out.write(',');
      out.write(' ');
      out.write('\'');
      out.print(request.getRemoteAddr());
      out.write('\'');
      out.write(',');
      out.write(' ');
      out.print(end);
      out.write(',');
      out.write(' ');
      out.print(comUserid);
      out.write(',');
      out.write(' ');
      out.print(nowBlock);
      out.write(',');
      out.write(' ');
      out.print(nowPage);
      out.write(',');
      out.write(' ');
      out.print(pagePerBlock);
      out.write(',');
      out.write(' ');
      out.print(totalPage);
      out.write(")\">수정</button>\r\n");
      out.write("	        </div>\r\n");
      out.write("		</form>\r\n");
      out.write("        \r\n");
      out.write("        <!-- 대댓글 폼 (숨김/답글버튼으로 토글) -->\r\n");
      out.write("        <form action=\"commentReply\" name=\"replyFrm\" id=\"replyFrm\" method=\"post\" autocomplete=\"off\" class=\"off\">\r\n");
      out.write("	        <div id=\"writeComment\">\r\n");
      out.write("	          <p class=\"commentAuthor\">\r\n");
      out.write("	            <span>답글</span>");
      out.print(loginNickname);
      out.write("\r\n");
      out.write("	          </p>\r\n");
      out.write("	          <textarea name=\"inputComment\" placeholder=\"답글을 작성해보세요!\"></textarea>\r\n");
      out.write("	          <button type=\"button\" onclick=\"replySubmit(");
      out.print(commentId);
      out.write(',');
      out.write(' ');
      out.print(loginId);
      out.write(',');
      out.write(' ');
      out.write('\'');
      out.print(loginNickname);
      out.write('\'');
      out.write(',');
      out.write(' ');
      out.print(num);
      out.write(',');
      out.write(' ');
      out.write('\'');
      out.print(request.getRemoteAddr());
      out.write('\'');
      out.write(',');
      out.write(' ');
      out.print(commentId);
      out.write(',');
      out.write(' ');
      out.print(comDepth);
      out.write(',');
      out.write(' ');
      out.print(comPos);
      out.write(',');
      out.write(' ');
      out.print(end);
      out.write(',');
      out.write(' ');
      out.print(nowBlock);
      out.write(',');
      out.write(' ');
      out.print(nowPage);
      out.write(',');
      out.write(' ');
      out.print(pagePerBlock);
      out.write(',');
      out.write(' ');
      out.print(totalPage);
      out.write(")\">작성</button>\r\n");
      out.write("	        </div>\r\n");
      out.write("		</form>\r\n");
      out.write("		\r\n");
      out.write("        ");
 // status=9면서 대댓이있는건 내용대체출력+버튼미출력
   		  } else if(comStatus==9) { 
      out.write("\r\n");
      out.write("        	<div class=\"comment comment-");
      out.print(num);
      out.write(" comid-");
      out.print(commentId);
      out.write("\r\n");
      out.write("    		");
if(comDepth > 0) {
      out.write(" depth depth-");
      out.print(comDepth);
      out.write("\"\r\n");
      out.write("    		");
 int depthPx = comDepth <= 16 ?  (30 * comDepth) : (30 * 16); 
      out.write("\r\n");
      out.write("    		style=\"margin-left: ");
      out.print(depthPx);
}
      out.write("px;\">\r\n");
      out.write("	          <div class=\"commentMsg\">\r\n");
      out.write("	            <p class=\"text\">삭제된 댓글입니다.</p>\r\n");
      out.write("	          </div>\r\n");
      out.write("        	</div> <!-- comment -->\r\n");
      out.write("        ");
 } // else if(status==9)
     	} //for(int i=0; i<forCount; i++) 
      out.write("\r\n");
      out.write("    ");
 } // if(!clist.isEmpty())
      out.write("\r\n");
      out.write("  	</div> <!--commentCont-->\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<!-- 페이지네이션 -->\r\n");
      out.write("	");
// 게시글이 존재한다면 (totalPage 검사) 페이지네이션 생성(현재블럭의 첫페이지~끝페이지)
       if(totalPage != 0) { 
      out.write("\r\n");
      out.write("        <ul id=\"comPagination\">\r\n");
      out.write("        ");

        // 현재 페이지블럭이 첫블럭이 아니라면 '이전블럭으로', '처음페이지로' 버튼 생성
        if(nowBlock > 1) { 
      out.write("\r\n");
      out.write("	        <li class=\"pageBtn btnFirst\" title=\"첫 페이지로\" onclick=\"goComBlock(this, ");
      out.print(num);
      out.write(',');
      out.write(' ');
      out.print(nowBlock);
      out.write(',');
      out.write(' ');
      out.print(pagePerBlock);
      out.write(',');
      out.write(' ');
      out.print(totalPage );
      out.write(',');
      out.write(' ');
      out.print(end);
      out.write(");\"><i class=\"fa-solid fa-angles-left\"></i></li>\r\n");
      out.write("	        <li class=\"pageBtn btnPrev\" title=\"이전 페이지로\"  onclick=\"goComBlock(this, ");
      out.print(num);
      out.write(',');
      out.write(' ');
      out.print(nowBlock);
      out.write(',');
      out.write(' ');
      out.print(pagePerBlock);
      out.write(',');
      out.write(' ');
      out.print(totalPage );
      out.write(',');
      out.write(' ');
      out.print(end);
      out.write(");\"><i class=\"fa-solid fa-angle-left\"></i></li>\r\n");
      out.write("      ");
} //if(nowBlock > 1)
       	
       	
      for(int nPage=pageStart; nPage<pageEnd; nPage++) { 
      out.write("\r\n");
      out.write("		<!-- 클릭한 페이지네이션nPage과 클릭시 전송받은 nowPage와 같다면 스타일 적용(li에 class=\"on\") -->\r\n");
      out.write("		<li onclick=\"goComPage(");
      out.print(num);
      out.write(',');
      out.write(' ');
      out.print(nowBlock);
      out.write(',');
      out.write(' ');
      out.print(pagePerBlock);
      out.write(',');
      out.write(' ');
      out.print(totalPage );
      out.write(',');
      out.write(' ');
      out.print(nPage);
      out.write(',');
      out.write(' ');
      out.print(end);
      out.write(")\"\r\n");
      out.write("		");
 if(nowPage == nPage) { 
      out.write("class=\"on\" ");
 } 
      out.write('>');
      out.print(nPage);
      out.write("</li>\r\n");
      out.write("	  ");
} //for(int nPage=pageStart; nPage<pageEnd; nPage++)

		// 현재 페이지블럭이 마지막블럭이 아니라면 '다음블럭으로', '마지막페이지로' 버튼생성
	 		if(totalBlock > nowBlock) { 
      out.write("\r\n");
      out.write("			<li class=\"pageBtn btnNext\" title=\"다음 페이지로\" onclick=\"goComBlock(this, ");
      out.print(num);
      out.write(',');
      out.write(' ');
      out.print(nowBlock);
      out.write(',');
      out.write(' ');
      out.print(pagePerBlock);
      out.write(',');
      out.write(' ');
      out.print(totalPage );
      out.write(',');
      out.write(' ');
      out.print(end);
      out.write(");\"><i class=\"fa-solid fa-angle-right\"></i></li>\r\n");
      out.write("	   		<li class=\"pageBtn btnLast\" title=\"마지막 페이지로\" onclick=\"goComBlock(this, ");
      out.print(num);
      out.write(',');
      out.write(' ');
      out.print(nowBlock);
      out.write(',');
      out.write(' ');
      out.print(pagePerBlock);
      out.write(',');
      out.write(' ');
      out.print(totalPage );
      out.write(',');
      out.write(' ');
      out.print(end);
      out.write(");\"><i class=\"fa-solid fa-angles-right\"></i></li>\r\n");
      out.write("	   	");
 } //if(totalBlock > nowBlock) 
      out.write("\r\n");
      out.write("       	</ul> <!--#pagination-->\r\n");
      out.write("     ");
 } // if(totalPage != 0)
      out.write("\r\n");
      out.write("       \r\n");
      out.write("   \r\n");
      out.write("	");
 // 로그인 되어있을 때만 댓글폼 노출
		if(loginId != null) { 
		 	
		 	// 오늘날짜 추출
		 	// String today = dMgr.getToday(); --페이지가 로드되었을 때 기준시각
		
      out.write("\r\n");
      out.write("			<form name=\"commentFrm\" id=\"commentFrm\" method=\"post\" autocomplete=\"off\">\r\n");
      out.write("		        <div id=\"writeComment\">\r\n");
      out.write("		          <p class=\"commentAuthor\">\r\n");
      out.write("		            ");
      out.print(loginNickname);
      out.write("\r\n");
      out.write("		          </p>\r\n");
      out.write("		          <textarea name=\"inputComment\" placeholder=\"댓글을 작성해보세요!\"></textarea>\r\n");
      out.write("		          <button type=\"button\" onclick=\"comSubmit(");
      out.print(loginId);
      out.write(',');
      out.write(' ');
      out.write('\'');
      out.print(loginNickname);
      out.write('\'');
      out.write(',');
      out.write(' ');
      out.print(num);
      out.write(',');
      out.write(' ');
      out.write('\'');
      out.print(request.getRemoteAddr());
      out.write('\'');
      out.write(',');
      out.write(' ');
      out.print(start);
      out.write(',');
      out.write(' ');
      out.print(end);
      out.write(")\">작성</button>\r\n");
      out.write("		        </div>\r\n");
      out.write("			</form>\r\n");
      out.write("	");
 } else { 
      out.write("\r\n");
      out.write("			<div id=\"loginNotice\">\r\n");
      out.write("				<p>로그인 이후에 댓글을 작성할 수 있습니다.</p>\r\n");
      out.write("				<a href=\"/login/login01\">로그인</a>\r\n");
      out.write("			</div>\r\n");
      out.write("	");
 } 
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
