/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.96
 * Generated at: 2024-11-15 06:51:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.login;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.math.BigInteger;
import java.security.SecureRandom;
import java.net.URLEncoder;

public final class login01_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("java.security.SecureRandom");
    _jspx_imports_classes.add("java.net.URLEncoder");
    _jspx_imports_classes.add("java.math.BigInteger");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 
// 아이디저장 쿠키반영
String saveId = "";
Cookie[] cookies = request.getCookies();
if(cookies!=null){
	for(int i = 0; i < cookies.length; i++){
		if(cookies[i].getName().equals("saveId")){
			saveId = cookies[i].getValue();
			break; // 쿠키를 찾으면 반복 종료
		}//if
	}//for
}//if

if (session.getAttribute("idKeyS") != null) {
    
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        alert(\"로그인 상태입니다. 메인화면으로 이동합니다.\");\r\n");
      out.write("        location.href=\"/\";\r\n");
      out.write("    </script>\r\n");
      out.write("    ");

    return;
}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\"> \r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("  <title>로그인 | 은하수책방</title>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/reset.css?after\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/index.css?after\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/login01.css?after\" />\r\n");
      out.write("  <script defer src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/header.js?after\"\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  <div id=\"wrap\">\r\n");
      out.write("\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../components/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <section class=\"login\">\r\n");
      out.write("      <h2>로그인</h2>\r\n");
      out.write("      <form name=\"loginFrm\" method=\"post\" action=\"/procs/loginProc\">\r\n");
      out.write("        <div id=\"idInput\">\r\n");
      out.write("          <label for=\"id\">아이디</label>\r\n");
      out.write("          ");

          if(saveId.equals("")){
        	  
      out.write("\r\n");
      out.write("        	  <input type=\"text\" name=\"id\" id=\"id\" placeholder = \"abc@naver.com\">\r\n");
      out.write("        	  ");

          }else{
        	  
      out.write("\r\n");
      out.write("        	  <input type=\"text\" name=\"id\" id=\"id\" placeholder = \"이메일형식\" value=\"");
      out.print(saveId);
      out.write("\">\r\n");
      out.write("        	  ");

          }
          
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"pwdInput\">\r\n");
      out.write("          <label for=\"pwd\">비밀번호</label>\r\n");
      out.write("          <input type=\"password\" name=\"pwd\" id=\"pwd\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div>\r\n");
      out.write("          ");

          if(saveId.equals("")){
        	  
      out.write("\r\n");
      out.write("        	  <input type=\"checkbox\" name=\"saveId\" id=\"saveId\" value=\"saveId\" />\r\n");
      out.write("        	  ");

          }else{
        	  
      out.write("\r\n");
      out.write("        	  <input type=\"checkbox\" name=\"saveId\" id=\"saveId\" value=\"saveId\" checked />\r\n");
      out.write("        	  ");

          }
          
      out.write("\r\n");
      out.write("          <label for=\"saveId\">아이디 저장</label>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <button type=\"button\" onclick=\"loginChk()\">로그인</button>\r\n");
      out.write("        \r\n");
      out.write("     	");

		String clientId = "cR6ZYmE3B8jjB8ERbb3U";//애플리케이션 클라이언트 아이디값";
		String redirectURI = URLEncoder.encode("http://localhost:8080/login/naverLogin", "UTF-8"); ///login/naverLogin으로 이동
		SecureRandom random = new SecureRandom();
		String state = new BigInteger(130, random).toString();
		String apiURL = "https://nid.naver.com/oauth2.0/authorize?response_type=code";
		apiURL += "&client_id=" + clientId;
		apiURL += "&redirect_uri=" + redirectURI;
		apiURL += "&state=" + state;
		session.setAttribute("state", state);
		
      out.write("\r\n");
      out.write("		<a class=\"naver\" href=\"");
      out.print(apiURL);
      out.write("\">\r\n");
      out.write("			<img height=\"50\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/btnG_완성형.png\"/>\r\n");
      out.write("		</a>\r\n");
      out.write("        \r\n");
      out.write("      </form>\r\n");
      out.write("      <div id=\"loginMng\">\r\n");
      out.write("        <a href=\"/signup/signup01\">회원가입</a>\r\n");
      out.write("        ㅣ\r\n");
      out.write("        <a href=\"/login/login02\">비밀번호 찾기</a>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </section>\r\n");
      out.write("	<footer>\r\n");
      out.write("      <address>&copy;Designed by teamMillkyWay</address>\r\n");
      out.write("    </footer>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("  <script>\r\n");
      out.write("    // 유효성검사\r\n");
      out.write("    const $frm = document.loginFrm;\r\n");
      out.write("    $frm.id.focus();\r\n");
      out.write("    function loginChk() {\r\n");
      out.write("      if($frm.id.value == null || $frm.id.value == \"\") {\r\n");
      out.write("        alert(\"아이디를 입력해주세요.\");\r\n");
      out.write("        $frm.id.focus();\r\n");
      out.write("        return;\r\n");
      out.write("      }\r\n");
      out.write("      if($frm.pwd.value == null || $frm.pwd.value == \"\") {\r\n");
      out.write("        alert(\"비밀번호를 입력해주세요.\");\r\n");
      out.write("        $frm.pwd.focus();\r\n");
      out.write("        return;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      $frm.submit();\r\n");
      out.write("    }\r\n");
      out.write("  </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
